language: php

php:
    - 5.3
    - 5.4

before_script:
    - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer self-update
    - composer install --prefer-dist

script: bin/phpspec run --format=pretty
